 /*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package cuvankhoa.bankingmanagement.view;

import cuvankhoa.bankingmanagement.model.Atm;
import cuvankhoa.bankingmanagement.model.Customer;
import cuvankhoa.bankingmanagement.view.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author TOTORO
 */
public class FindATM extends javax.swing.JDialog {

    /**
     * Creates new form AddATM
     */
    MainWindow mainWindow;
    DefaultTableModel dtm;
    public FindATM(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.mainWindow = (MainWindow)parent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ATMID = new javax.swing.JLabel();
        txtID = new javax.swing.JTextField();
        address = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        txtCash = new javax.swing.JTextField();
        ATMID2 = new javax.swing.JLabel();
        ATMID3 = new javax.swing.JLabel();
        txt50 = new javax.swing.JTextField();
        txt100 = new javax.swing.JTextField();
        ATMID4 = new javax.swing.JLabel();
        txt200 = new javax.swing.JTextField();
        ATMID5 = new javax.swing.JLabel();
        txt500 = new javax.swing.JTextField();
        ATMID6 = new javax.swing.JLabel();
        cbxStatus = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        cancel = new javax.swing.JButton();
        add = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        atmTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Add ATM");
        setResizable(false);

        ATMID.setText("ATMID");

        txtID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIDActionPerformed(evt);
            }
        });

        address.setText("Address");

        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });

        txtCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCashActionPerformed(evt);
            }
        });

        ATMID2.setText("Cash ");

        ATMID3.setText("50quanity");

        txt50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt50ActionPerformed(evt);
            }
        });

        txt100.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt100ActionPerformed(evt);
            }
        });

        ATMID4.setText("100quanity");

        txt200.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt200ActionPerformed(evt);
            }
        });

        ATMID5.setText("200quanity");

        txt500.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt500ActionPerformed(evt);
            }
        });

        ATMID6.setText("500quanity");

        cbxStatus.setSelected(true);

        jLabel1.setText("Status");

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        add.setText("Find");
        add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addActionPerformed(evt);
            }
        });

        jScrollPane2.setRequestFocusEnabled(false);

        atmTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "ATMID", "Address", "Cash", "50quanity", "100quanity", "200quanity", "500quanity", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Boolean.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        atmTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        atmTable.setEditingColumn(0);
        atmTable.setEditingRow(0);
        atmTable.setEnabled(false);
        atmTable.setFocusable(false);
        atmTable.setGridColor(new java.awt.Color(204, 204, 204));
        atmTable.setRowSelectionAllowed(false);
        atmTable.setSelectionBackground(new java.awt.Color(204, 204, 204));
        atmTable.setSelectionForeground(new java.awt.Color(204, 204, 204));
        atmTable.setShowGrid(true);
        atmTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(atmTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ATMID6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ATMID5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ATMID4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ATMID3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ATMID2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(address, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(ATMID, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(txt500, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txt200, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txt100, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txt50, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txtCash, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                            .addComponent(txtID)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(add)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ATMID))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(address))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCash, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ATMID2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ATMID3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ATMID4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt200, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ATMID5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txt500, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ATMID6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbxStatus)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cancel)
                            .addComponent(add))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIDActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCashActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCashActionPerformed

    private void txt50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt50ActionPerformed

    private void txt100ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt100ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt100ActionPerformed

    private void txt200ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt200ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt200ActionPerformed

    private void txt500ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt500ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt500ActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
       this.dispose();
    }//GEN-LAST:event_cancelActionPerformed

    private void addActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addActionPerformed
        Atm a = new Atm("*", "*", mainWindow.currentBank.getName(), -1, -1, 
                -1, -1, -1, true, null, null, null, null, null);
        dtm = (DefaultTableModel)atmTable.getModel();
        // clear table
        int rows = dtm.getRowCount();
        for(int i = rows-1;i>=0;i--)
        {
            dtm.removeRow(i);
        }
        int condition = 0; // nho nhat la 1, lon nhat bang 12
        int stt = 1;
        // nhan input
        if(txtID.getText().length()>0){
            a.setAtmID(txtID.getText());
            condition++;}
        if(txtAddress.getText().length()>0){
            a.setAddress(txtAddress.getText());
            condition++; }
        if(txtCash.getText().length()>0){
            a.setCash(Integer.parseInt(txtCash.getText()));
            condition++;
        }
        if(txt50.getText().length()>0){
            a.setQuanity50(Integer.parseInt(txt50.getText()));
            condition++;
        }
        if(txt100.getText().length()>0){
            a.setQuanity100(Integer.parseInt(txt100.getText()));
            condition++;
        }
        if(txt200.getText().length()>0){
            a.setQuanity200(Integer.parseInt(txt200.getText()));
            condition++;
        }
        if(txt500.getText().length()>0){
            a.setQuanity500(Integer.parseInt(txt500.getText()));
            condition++;
        }
        a.setStatus(cbxStatus.isSelected());
        condition++;
        System.out.println(condition);
        //if(condition>0){
            for(Atm i: mainWindow.currentBank.getAtm())
            {
                int conditionPass = 0;
                if(i.getAtmID().contains(a.getAtmID()))
                {
                    conditionPass++;
                }
                if(i.getAddress().contains(a.getAddress()))
                {
                    conditionPass++;
                }
                if(a.getCash()==i.getCash())
                {
                    conditionPass++;
                }
                if(a.getQuanity50()==i.getQuanity50())
                {
                    conditionPass++;
                }
                if(a.getQuanity100()==i.getQuanity100())
                {
                    conditionPass++;
                }
                if(a.getQuanity200()==i.getQuanity200())
                {
                    conditionPass++;
                }
                if(a.getQuanity500()==i.getQuanity500())
                {
                    conditionPass++;
                }
                if(a.isStatus()==i.isStatus())
                {
                    conditionPass++;
                }
                System.out.println(conditionPass);
                if(conditionPass == condition)
                {
                    // them du lieu ra bang
                    dtm.addRow(new Object[]{
                stt, i.getAtmID(), i.getAddress(),i.getCash(),i.getQuanity50(), i.getQuanity100(), i.getQuanity200()
                        , i.getQuanity500(), i.isStatus()
                });
                    stt++;
                }
            }
    }//GEN-LAST:event_addActionPerformed

    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ATMID;
    private javax.swing.JLabel ATMID2;
    private javax.swing.JLabel ATMID3;
    private javax.swing.JLabel ATMID4;
    private javax.swing.JLabel ATMID5;
    private javax.swing.JLabel ATMID6;
    private javax.swing.JButton add;
    private javax.swing.JLabel address;
    private javax.swing.JTable atmTable;
    private javax.swing.JButton cancel;
    private javax.swing.JCheckBox cbxStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField txt100;
    private javax.swing.JTextField txt200;
    private javax.swing.JTextField txt50;
    private javax.swing.JTextField txt500;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtCash;
    private javax.swing.JTextField txtID;
    // End of variables declaration//GEN-END:variables
}
